################
# DrupalCI includes:
# As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
# View these include files at https://git.drupalcode.org/project/gitlab_templates/
################
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
################
variables:
  OPT_IN_TEST_CURRENT: 1
  OPT_IN_TEST_MAX_PHP: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_DRUPAL8: 1
  RUN_JOB_UPGRADE_STATUS: 1
  _SHOW_ENVIRONMENT_VARIABLES: 1
  _PHPUNIT_CONCURRENT: 1
  _PHPUNIT_TESTGROUPS: ''

################
# Job overrides
################

.show-variables: &show-variables
  - |
    printf "CI_PIPELINE_SOURCE          = %s\n" $CI_PIPELINE_SOURCE &&
    printf "CI_DEFAULT_BRANCH           = %s\n" $CI_DEFAULT_BRANCH &&
    printf "CI_COMMIT_BRANCH            = %s\n" $CI_COMMIT_BRANCH &&
    printf "CI_COMMIT_TAG               = %s\n" $CI_COMMIT_TAG &&
    printf "CI_COMMIT_TITLE             = %s\n" "$CI_COMMIT_TITLE" &&
    printf "CI_MERGE_REQUEST_IID        = %s\n" $CI_MERGE_REQUEST_IID &&
    printf "CI_MERGE_REQUEST_TITLE      = %s\n" "$CI_MERGE_REQUEST_TITLE" &&
    printf "CI_PROJECT_ROOT_NAMESPACE   = %s\n" $CI_PROJECT_ROOT_NAMESPACE &&
    printf "CI_PAGES_URL                = %s\n" $CI_PAGES_URL &&
    printf "CI_PROJECT_NAME             = %s\n" $CI_PROJECT_NAME &&
    printf "CI_JOB_NAME                 = %s\n" "$CI_JOB_NAME" &&
    printf "CI_JOB_NAME chopped         = %s\n" "${CI_JOB_NAME%:*}" &&
    printf "DRUPAL_CORE                 = %s\n" $DRUPAL_CORE &&
    printf "PHP_VERSION                 = %s\n" $PHP_VERSION &&
    printf "MODULE_NAME                 = %s\n" $MODULE_NAME

# -------------------------------- BUILD ---------------------------------------

.opt-in-drupal8-rule: &opt-in-drupal8-rule
  if: '$OPT_IN_TEST_DRUPAL8 != "1"'
  when: never

# Re-usable rule for running the job automatically on Merge Requests and allowing it
# to manually triggered for all other types of pipeline.
# Using 'when: manual' needs 'allow failure: true' otherwise the overall pipeline status
# is shown as 'blocked' and the stages show 'running' without ever appearing to finish.
.manual-if-not-mr-rule: &manual-if-not-mr-rule
  - if: $CI_PIPELINE_SOURCE != "merge_request_event"
    when: manual
    allow_failure: true
  - when: on_success

.composer-base:
  before_script:
    # If testing against Drupal 11 then swap in a different composer file to load dev versions and
    # merge-request branches of several third-party modules which which do not have a fully compatible release yet.
    - if [[ $DRUPAL_CORE =~ ^11 ]]; then rm composer.json; mv composer_for_d11_testing.json composer.json; echo "Using composer_for_d11_testing.json"; fi;
  after_script:
    - !reference [ .create-environment-variables ]
    # Show the last two commits. Current directory /builds/project/scheduler ($CI_PROJECT_DIR) is correct.
    - git show -2 --stat --oneline
    - *show-variables
    # - cat composer.json
    - COLUMNS=120 composer show | grep -E '\/(core |rules|commerce|entity|inline_entity_form|workbench|drush|devel_generate|address)'

composer (max PHP version):
  # Using when: manual needs 'allow failure: true' otherwise the overall pipeline status shows 'blocked'
  rules:
    - !reference [ .opt-in-max-php-rule ]
    - when: manual
      allow_failure: true

composer (previous minor):
  rules:
    - !reference [ .opt-in-previous-minor-rule ]
    - when: manual
      allow_failure: true

composer (previous major):
  rules:
    - !reference [ .opt-in-previous-major-rule ]
    - *manual-if-not-mr-rule

composer (next minor):
  rules:
    - !reference [ .opt-in-next-minor-rule ]
    - when: manual
      allow_failure: true

composer (next major):
  rules:
    - !reference [ .opt-in-next-major-rule ]
    - *manual-if-not-mr-rule

composer (drupal 8):
  extends: .composer-base
  rules:
    - *opt-in-drupal8-rule
    - *manual-if-not-mr-rule
  variables:
    PHP_VERSION: 7.4
    DRUPAL_CORE: 8.9.20

# -------------------------------- VALIDATE ------------------------------------

eslint:
  allow_failure: false
  after_script:
    - cd $CI_PROJECT_DIR/$_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
    - test -f .eslintignore && echo "===  This is .eslintignore  ===" && cat .eslintignore || true
    - test -f .prettierignore && echo "=== This is .prettierignore ===" && cat .prettierignore || true

stylelint:
  allow_failure: false

phpcs:
  allow_failure: false

phpstan:
  after_script:
    - test -f phpstan.neon && echo "=== This is phpstan.neon ===" && cat phpstan.neon
    - php $CI_PROJECT_DIR/scripts/phpstan-baseline-summary.php phpstan-baseline-to-fix.neon

# -------------------------------- TEST ----------------------------------------

phpunit:
  parallel:
    matrix:
      # Run test groups in parallel. This also speeds up identification of failing tests.
      # @todo put back "scheduler_drush" when https://www.drupal.org/i/3359998 is solved.
      - _MATRIX_VALUE:
        - scheduler
        - scheduler_api
        # - scheduler_drush
        - scheduler_js
        - scheduler_kernel
        - scheduler_rules_integration
  before_script:
    # If any variation also needs a before_script then add - !reference [phpunit, before_script] to include this script.
    - *show-variables
    - |
      printf "_MATRIX_VALUE               = %s\n" $_MATRIX_VALUE &&
      printf "_PHPUNIT_CONCURRENT         = %s\n" $_PHPUNIT_CONCURRENT &&
      printf "_PHPUNIT_TESTGROUPS         = %s\n" "$_PHPUNIT_TESTGROUPS" &&
      printf "_PHPUNIT_EXTRA              = %s\n" "$_PHPUNIT_EXTRA" &&
      printf "SYMFONY_DEPRECATIONS_HELPER = %s\n" $SYMFONY_DEPRECATIONS_HELPER
    - |
      if [[ "$_MATRIX_VALUE" != "" ]]; then
        if [[ "$_PHPUNIT_CONCURRENT" == "0" ]]; then
          # Specify parameters that will be passed to PHPUNIT (needs --group)
          export _PHPUNIT_EXTRA="$_PHPUNIT_EXTRA --group $_MATRIX_VALUE"
        else
          # Specify parameters that will be passed to RUN-TESTS.SH (without --group)
          export _PHPUNIT_EXTRA="$_PHPUNIT_EXTRA $_MATRIX_VALUE"
          # Ensure the value is 1 if it is not 0.
          export _PHPUNIT_CONCURRENT=1
        fi
      fi
    # Patch to disable strict config schema validation on older versions of core.
    # See https://www.drupal.org/project/scheduler/issues/3451750
    - if [[ $DRUPAL_CORE =~ ^(8.9|9.5|10.2) ]]; then patch -p1 --verbose < tests/3451750-strict-config-schema.patch; fi
    - echo "End of before_script _PHPUNIT_CONCURRENT=$_PHPUNIT_CONCURRENT _PHPUNIT_EXTRA=$_PHPUNIT_EXTRA"

phpunit (next minor):
  variables:
    # Use core ignoreFile to show deprecations. This is only used when $_PHPUNIT_CONCURRENT=1 so make sure that is also set.
    _PHPUNIT_CONCURRENT: 1
    SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=$CI_PROJECT_DIR/$_WEB_ROOT/core/.deprecation-ignore.txt"

phpunit (next major):
  variables:
    # Use core ignoreFile to show deprecations. This is only used when $_PHPUNIT_CONCURRENT=1 so make sure that is also set.
    _PHPUNIT_CONCURRENT: 1
    SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=$CI_PROJECT_DIR/$_WEB_ROOT/core/.deprecation-ignore.txt"

phpunit (drupal 8):
  extends: phpunit
  rules:
    - *opt-in-drupal8-rule
    - !reference [ .skip-phpunit-rule ]
    - !reference [ .phpunit-tests-exist-rule ]
    - when: on_success
  needs:
    - "composer (drupal 8)"
  allow_failure: true

test-only changes:
  # Remove the parallel definition that is defined in the customized phpunit.
  parallel:

upgrade status:
  rules:
    - !reference [ .skip-upgrade-status-rule ]
    - when: manual
      allow_failure: true
