rsvplist.settings:
  type: config_object
  label: RSVP List Content Type Settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types on which the RSVP form can display
      sequence:
        type: string
        label: Content type
